// movie-recommendation-react/src/App.js
import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useState } from 'react';
import axios from 'axios';

const App = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] = useState([]);

  const handleSearch = async () => {
    try {
      const response = await axios.post('/title', { title: searchTerm });
      setSearchResults(response.data);
    } catch (error) {
      console.error('Error fetching search results:', error);
    }
  };

  const handleChange = (event) => {
    setSearchTerm(event.target.value);
  };

  return (
    <div className="container">
      <div className="row">
        <div className="col">
          <div className="input-group my-3">
            <input
              type="text"
              className="form-control"
              placeholder="Search movies..."
              value={searchTerm}
              onChange={handleChange}
            />
            <button className="btn btn-primary" onClick={handleSearch}>
              Search
            </button>
          </div>
          <div>
            {searchResults.length > 0 ? (
              <ul className="list-group">
                {searchResults.map((movie, index) => (
                  <li className="list-group-item" key={index}>
                    {movie.title}
                  </li>
                ))}
              </ul>
            ) : (
              <p>No results found.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default App;

// movie-recommondation-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { MovieService } from './services/movieService';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'movie-recommondation-ng';
  searchTxt: any;
  movies:any

  constructor(private movieService: MovieService) {

  }

  sampleFns() {
    this.movieService.getMovieDetails(this.searchTxt).subscribe((data) => {
      this.movies = data;
    });

    //console.log(this.searchTxt)
  }
}

<div>
  <div class="row">
    <div class="col-9">
        <input class="form-control" [(ngModel)]=searchTxt  type="text" placeholder="Search Movie" id="Search">
    </div>
    <div class="col-3">
      <button class="btn btn-primary" (click)="sampleFns()">Search</button>
    </div>
  </div>

  <div *ngIf=movies>
    <div style=" display: flex; flex-wrap: wrap;" *ngFor="let m of movies">
      <div class="col-4" style=" display: flex; flex-wrap: wrap;">
        {{m.results[0]?.originalTitleText.text}}
      </div>
    </div>

  </div>
</div>
